# Generated by Django 6.1.1 on 2026-09-06 14:09

import retro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(default=retro.models.generate_token, max_length=32, unique=True)),
            ],
        ),
    ]
